global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'java_bench'
    static_configs:
      - targets: ['localhost:20000']